version: '3'
services:
  db-mongo:
    image: mvertes/alpine-mongo:latest
    networks:
      - back-tier
    volumes:
      - db-data:/data/db-data
  backend:
    build: .
    volumes:
      - .:/app
      - dependencies:/app/node_modules
    links:
      - db-mongo
    networks:
      - front-tier
      - back-tier
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
volumes:
  dependencies:
  db-data:
